### ISSUE TITLE
Default @everyone

### ISSUE THREAD

**Issue by ZenithVal** [egebilecen/PZServerDiscordBot#101]
It does not need to @ everyone during initial setup.
Just a pinged a server of 500 by mistake.

**Comment by egebilecen** [comment]
Hey, it is there because when some discord servers have bunch of channels, it becomes hard to find the installation instructions and not everyone reads the README.md file, unfortunately. Also, it seems like you guys had some trouble with installation because you need to stop the bot and start it over and over again to get that much @. You can also always disable @ for your server and for bot too.
