### ISSUE TITLE
[BUG] Bot Not Detecting Workshop Update

### ISSUE THREAD

**Issue by epikec** [egebilecen/PZServerDiscordBot#146]
**Describe the bug**
Hello! First of all, thank you for the bot. I had a bug that that have been persisting half a year from the bot to not detecting workshop update. I notice there's stack trace error on pzlog. Thank you

**Expected behavior**
Ability for the bot to be able checks steamworkshop update set by interval.

**Screenshots**
pzlog and server.bat in txt form provided in the attachment.
[pzbot.log](https://github.com/user-attachments/files/16300963/pzbot.log)
[server.bat.txt](https://github.com/user-attachments/files/16300979/server.bat.txt)

**Additional context**
As i remember, the bug occurred after updating the bot to v1.11. Before the the bot works on checking the steamworkshop update interval

**Comment by egebilecen** [comment]
Hello, thank you for your report. I have checked your logs. It seems the problem is that bot can't find your server's .ini file or it uses the wrong one. Are there multiple *.ini files in the `%USERPROFILE%\Zomboid\Server` directory? If there are, could you rename the non-relevant .ini file(s) to something else such as `server.ini.bak` and try the bot again?
