### ISSUE TITLE
[BUG] the bot doesn't respond to commands after re-invitation

### ISSUE THREAD

**Issue by Myumyu10** [egebilecen/PZServerDiscordBot#148]
Previously, I asked about using two Discord bots in one server. Currently, both bots use channel 'c' as the command channel. To set different command channels for the two bots, I removed one of the bots from the server. I then assigned channel 'a' as the command channel for the remaining bot. After that, I re-invited the removed bot and tried to assign channel 'b' as its command channel by sending commands to the previously responsive channel 'c'. However, it is not responding to any commands now, even though it shows as online. How can I resolve this issue?

**Comment by Myumyu10** [comment]
Additionally, when the removed bot was re-invited, it did send a message in the public channel, which both bots share, indicating that the server was opened.

**Comment by egebilecen** [comment]
Hey. Bot not responding issue usually occurs due to insufficient channel permissions or wrong gateway intent configuration. See the warning below [here](https://github.com/egebilecen/PZServerDiscordBot?tab=readme-ov-file#writing-the-discord-bot-token-into-file). If you setup the gateway intent configuration correctly, it highly suggests the problem is due to discord server/channel permission so I can't really help on that. Maybe try to assign specific bots to specific channel from the channel configuration?

**Comment by Myumyu10** [comment]
thank u for ur helping. actually the bots had proper permission as i assigned them administer. it just fixed itself after like 30mins automatically. i guess it needed time to work after they re-invited.
